#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Set VIM
export EDITOR=/usr/bin/vim
export VISUAL=/usr/bin/vim

# AWS
export PATH=~/.local/bin:$PATH

# Postgres
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin

# Haskell
# export PATH=$PATH:/Users/fandrade/.local/bin

# Git
alias gfo='git fetch origin -p'

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

export PATH="$PATH:`yarn global bin`"

# Locale
export LANGUAGE="en_US.UTF-8" LANG="en_US.UTF-8" LC_IDENTIFICATION="en_US.UTF-8" LC_TELEPHONE="en_US.UTF-8" LC_TIME="en_US.UTF-8" LC_NUMERIC="en_US.UTF-8" LC_PAPER="en_US.UTF-8" LC_MEASUREMENT="en_US.UTF-8" LC_ADDRESS="en_US.UTF-8" LC_MONETARY="en_US.UTF-8" LC_NAME="en_US.UTF-8" LC_CTYPE="en_US.UTF-8"
